### ISSUE TITLE
about the STM8 develop environment

### ISSUE THREAD

**Issue by hanshuizhizi** [alsav/stm8-cc1101-baby-monitor#1]
hi:
which kind of compilor you are used in "stm8-cc1101-baby-monitor" project? i find that compilor name is sdcc in Makefile. 
are you develop this project on linux?

**Comment by alsav** [comment]
Hi!
Yes, I developed and flashed this project on linux ubuntu 14.04 host. You can download sdcc sources here https://sourceforge.net/projects/sdcc/files/ and then compile it with stm8 support. 
For flashing mcu I used Versaloon programmer with vsprog software. But you also can use more common programmer ST-LINK V2 with stm8flash software (https://github.com/vdudouyt/stm8flash). 
In a makefile, in this case you just need to add these lines:
_flash_stlink:
     stm8flash -c stlinkv2 -p stm8s003 -w $(OUT_DIR)/$(SRC).ihx_
and then run "make flash_stlink".

**Comment by hanshuizhizi** [comment]
Hi,alsav
How can i do to make sdcc support stm8 MCU?
By the way,does it support any debug tools like gdb or others?
thanks very much!

**Comment by alsav** [comment]
You can build sdcc from sources by _./configure && make && make install_ commands. By default it compiled with stm8 support.
As I know, gdb is not support stm8 targets, only stm32.
